# Generated by Django 4.1.4 on 2022-12-27 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('penalty_fee_amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'expired_payments',
            },
        ),
        migrations.CreateModel(
            name='Payment_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('paymentDate', models.DateField()),
                ('expirationDate', models.DateField()),
            ],
            options={
                'db_table': 'payment_user',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.AddField(
            model_name='payment_user',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='pagos.servicios'),
        ),
        migrations.AddField(
            model_name='payment_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expired_payments',
            name='payment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to='pagos.payment_user'),
        ),
    ]
