# Generated by Django 4.1.4 on 2022-12-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_expired_payments_payment_user_servicios_delete_pagos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired_payments',
            name='penalty_fee_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment_user',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment_user',
            name='paymentDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
